### ISSUE TITLE
Alembic 1.0.0 Library can't be build on RedHat 4 when using boost 1.48!

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nightstyles/alembic#273]
```
What steps will reproduce the problem?
1. build boost_thead library in boost 1.48
2. use python ../ALEMBIC_SOURCE/build/bootstrap/alembic_bootstrap.py . to 
generate the make file
3. use "make" to build the library, then there will be many build error

The error message just like below
---------------------------
/boost/1.48.0/include/boost/unordered/detail/allocator_helpers.hpp:406: error: 
`template<class T> static typename boost::disable_if_c< 
boost::unordered::detail::has_construct<Alloc,T>::value, void>::type 
boost::unordered::detail::allocator_traits::construct(Alloc&, T*, const T&) 
[with T = T, Alloc = std::allocator<boost::unordered::detail::ptr_bucket>]' and 
`template<class T> static typename boost::enable_if_c< 
boost::unordered::detail::has_construct<Alloc,T>::value, void>::type 
boost::unordered::detail::allocator_traits::construct(Alloc&, T*, const T&) 
[with T = T, Alloc = std::allocator<boost::unordered::detail::ptr_bucket>]' 
cannot be overloaded
/boost/1.48.0/include/boost/unordered/detail/allocator_helpers.hpp:422: error: 
`template<class T> static typename boost::disable_if_c< 
boost::unordered::detail::has_destroy<Alloc,T>::value, void>::type 
boost::unordered::detail::allocator_traits::destroy(Alloc&, T*) [with T = T, 
Alloc = std::allocator<boost::unordered::detail::ptr_bucket>]' and 
`template<class T> static typename boost::enable_if_c< 
boost::unordered::detail::has_destroy<Alloc,T>::value, void>::type 
boost::unordered::detail::allocator_traits::destroy(Alloc&, T*) [with T = T, 
Alloc = std::allocator<boost::unordered::detail::ptr_bucket>]' cannot be 
overloaded
make[2]: *** 
[lib/Alembic/AbcCoreHDF5/CMakeFiles/AlembicAbcCoreHDF5.dir/ApwImpl.cpp.o] Error 
1
make[2]: Leaving directory `/home/flame/Alembic/ALEMBIC_BUILD'
make[1]: *** [lib/Alembic/AbcCoreHDF5/CMakeFiles/AlembicAbcCoreHDF5.dir/all] 
Error 2
make[1]: Leaving directory `/home/flame/Alembic/ALEMBIC_BUILD'
make: *** [all] Error 2
---------------------------------- 

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
Alembic 1.0.0     RedHat4 GCC3.4.4

Please provide any additional information below.


```

Original issue reported on code.google.com by `alexzha...@gmail.com` on 8 Feb 2012 at 10:31
